-- MySQL Script generated by MySQL Workbench
-- Wed Feb 19 15:02:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema landsoluces
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema landsoluces
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `landsoluces` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `landsoluces`.`veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veiculos` (
  `id_veiculo` INT NOT NULL AUTO_INCREMENT,
  `nome_veiculo` VARCHAR(255) NULL,
  `placa_veiculo` VARCHAR(55) NULL,
  `seguro_veiculo` VARCHAR(3) NULL,
  `observacoes_veiculo` VARCHAR(555) NULL,
  PRIMARY KEY (`id_veiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landsoluces`.`veiculos atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veiculos atividade` (
  `id_vei_atv` INT NOT NULL AUTO_INCREMENT,
  `id_atividade` VARCHAR(255) NULL,
  `id_veiculo` VARCHAR(55) NULL,
  `create_date` DATE NULL,
  `create_by` INT NULL,
  `edit_by` INT NULL,
  `edit_date` DATE NULL,
  PRIMARY KEY (`id_vei_atv`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landsoluces`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade` (
  `id_atividade` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL DEFAULT "ID do funcionario (Tabela Usuario)",
  `km_inicial` VARCHAR(55) NULL,
  `km_final` VARCHAR(55) NULL,
  `data_atividade` DATE NULL,
  `observacoes` VARCHAR(555) NULL DEFAULT 'observações da atividade',
  PRIMARY KEY (`id_atividade`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `cena`.`permission_params` (`name`) VALUES ('veiculos_edit');
INSERT INTO `cena`.`permission_params` (`name`) VALUES ('veiculos_add');
INSERT INTO `cena`.`permission_params` (`name`) VALUES ('veiculos_delete');
INSERT INTO `cena`.`permission_params` (`name`) VALUES ('veiculos_view');


